version: 1.0.{build}

install:
- cmd: python -m pip install -U pip setuptools tox wheel

build_script:
- cmd: python setup.py bdist_wheel
- cmd: python -m pip install --only-binary --no-index --ignore-installed --find-links=dist/ vulture

test_script:
- cmd: vulture vulture/ tests/
- cmd: python -m vulture vulture/ tests/
- cmd: tox

matrix:
  fast_finish: true
