version: 1.0.{build}

install:
- cmd: python -m pip install -U pip setuptools tox wheel

build_script:
- cmd: python setup.py bdist_wheel
- cmd: pip --version
- cmd: python -m pip --version
- cmd: python3 -m pip --version
- cmd: python3 -m pip install --use-wheel --no-index --find-links=dist/ vulture

test_script:
- cmd: vulture vulture/ tests/
- cmd: python -m vulture vulture/ tests/
- cmd: tox

matrix:
  fast_finish: true
